#!/bin/bash

# Link in files, replacing whatever's already there.
ln -fs "dotfiles/bash/bashrc"           "${HOME}/.bashrc"
ln -fs "dotfiles/bash/screenrc"         "${HOME}/.screenrc"
ln -fs "dotfiles/bash/inputrc"          "${HOME}/.inputrc"
ln -fs "dotfiles/git/gitconfig"         "${HOME}/.gitconfig"
ln -fs "dotfiles/git/gitignore_global"  "${HOME}/.gitignore_global"
ln -fs "dotfiles/vim/vimrc"             "${HOME}/.vimrc"
ln -fs "dotfiles/vimperatorrc"          "${HOME}/.vimperatorrc"
ln -fs "dotfiles/X/Xdefaults"           "${HOME}/.Xdefaults"
ln -fs "dotfiles/X/xmodmap"             "${HOME}/.xmodmap"

rm -rf "${HOME}/.vim"
mkdir -p "${HOME}/.vim/bundle"
git clone https://github.com/gmarik/vundle.git "${HOME}/.vim/bundle/vundle"

vim +BundleInstall +qall

#If install ALL flag set then
if [ "$1" == "-a" ]; then
    rm -f "${HOME}/.xinitrc"
    cp "dotfiles/X/xinitrc"             "${HOME}/.xinitrc"
    rm -rf "${HOME}/.xmonad"
    cp "dotfiles/xmonad"                "${HOME}/.xmonad"
fi  
