set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdcommenter'
Bundle 'kien/ctrlp.vim'
Bundle 'ervandew/supertab'
Bundle 'myusuf3/numbers.vim'
Bundle 'bling/vim-airline'
Bundle 'flazz/vim-colorschemes'

filetype plugin indent on

syntax on
set bs=indent,eol,start
set hlsearch
set ruler

set t_Co=256
set laststatus=2

set tabstop=4
set expandtab
set shiftwidth=4 
set smarttab autoindent
set incsearch
set pastetoggle=<F2>
nnoremap <F3> :NumbersToggle<CR> 

colorscheme hornet

let mapleader=","

" Wildmenu
if has("wildmenu")
    set wildmenu
    set wildmode=longest:list
    if has("wildignore")
        set wildignore+=*.a,*.o
        set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
        set wildignore+=.DS_Store,.git,.hg,.svn
        set wildignore+=*~,*.swp,*.tmp
        set wildignore+=*.pyc,*.class,*.hi
    endif
    if exists("&wildignorecase")
        set wildignorecase
    endif
endif
